ChainItem:
  comment: Loads json data to   SF
  operation:
    - step: 1
      load_type: execute
      load_name: chain_item_json_stg_ld
      load_sql:  "sql/Supplylogix/ChainItem/chain_item_json_stg_ld.sql" 
    - step: 2
      load_type: execute
      load_name: chain_item_json_ld
      load_sql:  "sql/Supplylogix/ChainItem/chain_item_json_ld.sql" 
    - step: 3
      load_type: execute
      load_name: chain_item_ld
      load_sql:  "sql/Supplylogix/ChainItem/chain_item_ld.sql" 
 